In [13]:
import os
import pandas as pd
import numpy as np

#Gets a list of all of the file names for the pictures
def get_list_of_filenames(path:str) -> tuple:
    #dictionary = defaultdict(list)
    files = []
    ids = []
    for filename in os.listdir(path):
        if filename != '.DS_Store' and filename != '.ipynb_checkpoints' : #was not running due to a .ds_store file so I left it out
            files.append(path + '/' + filename)
            ids.append(filename[0:9])


    return (files,ids)

x = get_list_of_filenames('train_images')
all_pics = pd.DataFrame(x)

In [15]:
all_pics = all_pics.T

In [17]:
all_pics.columns = ['File','PetID']
all_pics

scored = pd.read_csv('10k_files_w_scores.csv')
scored

      Unnamed: 0  Unnamed: 0.1                         files  PetScore
0           7333          7333  train_images/0011d7c25-2.jpg       7.0
1           7334          7334  train_images/0011d7c25-3.jpg       7.0
2           7335          7335  train_images/0011d7c25-1.jpg       7.0
3           8393          8393  train_images/00156db4a-5.jpg       6.0
4           8394          8394  train_images/00156db4a-4.jpg       6.0
...          ...           ...                           ...       ...
9943        2727          2727  train_images/fff6f2f61-1.jpg       8.0
9944        4093          4093  train_images/fffa39a6a-2.jpg       6.0
9945        4094          4094  train_images/fffa39a6a-1.jpg       6.0
9946        2721          2721  train_images/fffd78a11-2.jpg      10.0
9947        2722          2722  train_images/fffd78a11-1.jpg      10.0

[9948 rows x 4 columns]

In [18]:
merged = pd.merge(all_pics,scored,how = 'outer',left_on = ['File'],right_on = ['files'])

In [22]:
merged = merged[['File','PetID','PetScore']]
merged

                               File      PetID  PetScore
0      train_images/2d725d001-3.jpg  2d725d001       NaN
1      train_images/bf9bd91e1-1.jpg  bf9bd91e1       NaN
2      train_images/9cb525274-3.jpg  9cb525274       3.0
3      train_images/16ffedcf8-7.jpg  16ffedcf8       NaN
4      train_images/a63364c39-1.jpg  a63364c39       6.0
...                             ...        ...       ...
58306  train_images/22c2f101e-2.jpg  22c2f101e       NaN
58307  train_images/a93eb0d6f-1.jpg  a93eb0d6f       NaN
58308  train_images/da7bed1f8-3.jpg  da7bed1f8       NaN
58309  train_images/d452218f1-1.jpg  d452218f1       NaN
58310  train_images/21fcd15c6-7.jpg  21fcd15c6       NaN

[58311 rows x 3 columns]

In [25]:
to_predict = merged[merged['PetScore'].isna()]
to_predict

                               File      PetID  PetScore
0      train_images/2d725d001-3.jpg  2d725d001       NaN
1      train_images/bf9bd91e1-1.jpg  bf9bd91e1       NaN
3      train_images/16ffedcf8-7.jpg  16ffedcf8       NaN
5      train_images/ea055de86-3.jpg  ea055de86       NaN
6      train_images/6b446b436-7.jpg  6b446b436       NaN
...                             ...        ...       ...
58306  train_images/22c2f101e-2.jpg  22c2f101e       NaN
58307  train_images/a93eb0d6f-1.jpg  a93eb0d6f       NaN
58308  train_images/da7bed1f8-3.jpg  da7bed1f8       NaN
58309  train_images/d452218f1-1.jpg  d452218f1       NaN
58310  train_images/21fcd15c6-7.jpg  21fcd15c6       NaN

[48363 rows x 3 columns]

In [26]:
train = merged[merged['PetScore'].notna()]
train

                               File      PetID  PetScore
2      train_images/9cb525274-3.jpg  9cb525274       3.0
4      train_images/a63364c39-1.jpg  a63364c39       6.0
9      train_images/76024f2ed-1.jpg  76024f2ed       7.0
14     train_images/7a12a494f-9.jpg  7a12a494f       7.0
17     train_images/4f0eacbdd-4.jpg  4f0eacbdd       7.0
...                             ...        ...       ...
58247  train_images/804e56f9b-2.jpg  804e56f9b       7.0
58283  train_images/28c34e5dc-2.jpg  28c34e5dc       7.0
58293  train_images/24e800fa6-3.jpg  24e800fa6       8.0
58299  train_images/afd3ded05-2.jpg  afd3ded05       4.0
58303  train_images/ae0a993ac-2.jpg  ae0a993ac       6.0

[9948 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_validate, y_train, y_validate = train_test_split(, y, random_state=1,train_size = .6,test_size = .4)